require_relative '../../node_modules/react-native-test-app/test_app'

workspace 'BlurExample.xcworkspace'

use_flipper! false unless ENV['ENABLE_FLIPPER']

options = {
  :fabric_enabled => false,
  :hermes_enabled => false,
  :turbomodule_enabled => false,
}

use_test_app! options do |target|
  target.tests do
  end
end